In [32]:
import pandas as pd

In [33]:
df = pd.read_csv(' https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/refs/heads/master/mtcars.csv')

In [34]:
df

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [35]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [36]:
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [37]:
df.tail()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [38]:
df.columns

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [41]:
#renaming column with car names as cartyp
df.rename(columns={'Unnamed: 0': 'cartyp'}, inplace=True)
df

,cartyp,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [44]:
df2 = df[['mpg','hp','wt','cyl']]
df2

     mpg   hp     wt  cyl
0   21.0  110  2.620    6
1   21.0  110  2.875    6
2   22.8   93  2.320    4
3   21.4  110  3.215    6
4   18.7  175  3.440    8
5   18.1  105  3.460    6
6   14.3  245  3.570    8
7   24.4   62  3.190    4
8   22.8   95  3.150    4
9   19.2  123  3.440    6
10  17.8  123  3.440    6
11  16.4  180  4.070    8
12  17.3  180  3.730    8
13  15.2  180  3.780    8
14  10.4  205  5.250    8
15  10.4  215  5.424    8
16  14.7  230  5.345    8
17  32.4   66  2.200    4
18  30.4   52  1.615    4
19  33.9   65  1.835    4
20  21.5   97  2.465    4
21  15.5  150  3.520    8
22  15.2  150  3.435    8
23  13.3  245  3.840    8
24  19.2  175  3.845    8
25  27.3   66  1.935    4
26  26.0   91  2.140    4
27  30.4  113  1.513    4
28  15.8  264  3.170    8
29  19.7  175  2.770    6
30  15.0  335  3.570    8
31  21.4  109  2.780    4

In [45]:
df2.rename(columns={'cyl': 'cylinder'}, inplace =True)
df2

/tmp/ipykernel_1646/3523959115.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'cyl': 'cylinder'}, inplace =True)

     mpg   hp     wt  cylinder
0   21.0  110  2.620         6
1   21.0  110  2.875         6
2   22.8   93  2.320         4
3   21.4  110  3.215         6
4   18.7  175  3.440         8
5   18.1  105  3.460         6
6   14.3  245  3.570         8
7   24.4   62  3.190         4
8   22.8   95  3.150         4
9   19.2  123  3.440         6
10  17.8  123  3.440         6
11  16.4  180  4.070         8
12  17.3  180  3.730         8
13  15.2  180  3.780         8
14  10.4  205  5.250         8
15  10.4  215  5.424         8
16  14.7  230  5.345         8
17  32.4   66  2.200         4
18  30.4   52  1.615         4
19  33.9   65  1.835         4
20  21.5   97  2.465         4
21  15.5  150  3.520         8
22  15.2  150  3.435         8
23  13.3  245  3.840         8
24  19.2  175  3.845         8
25  27.3   66  1.935         4
26  26.0   91  2.140         4
27  30.4  113  1.513         4
28  15.8  264  3.170         8
29  19.7  175  2.770         6
30  15.0  335  3.570         8
31  21.4  109  2.780         4

In [47]:
df2.describe()

             mpg          hp         wt   cylinder
count  32.000000   32.000000  32.000000  32.000000
mean   20.090625  146.687500   3.217250   6.187500
std     6.026948   68.562868   0.978457   1.785922
min    10.400000   52.000000   1.513000   4.000000
25%    15.425000   96.500000   2.581250   4.000000
50%    19.200000  123.000000   3.325000   6.000000
75%    22.800000  180.000000   3.610000   8.000000
max    33.900000  335.000000   5.424000   8.000000

In [54]:
#Vehicles with the most gas mileage (original data frame)
df[df['mpg']>30]

,cartyp,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2

In [55]:
#vehicles with the most gas mileage (df2)  (columns)
df2[df2['mpg']>30]

     mpg   hp     wt  cylinder
17  32.4   66  2.200         4
18  30.4   52  1.615         4
19  33.9   65  1.835         4
27  30.4  113  1.513         4

In [66]:
#vehicle labelled/named 14 in orginal dataset (rows)
df.loc[14]

cartyp    Cadillac Fleetwood
mpg                     10.4
cyl                        8
disp                   472.0
hp                       205
drat                    2.93
wt                      5.25
qsec                   17.98
vs                         0
am                         0
gear                       3
carb                       4
Name: 14, dtype: object

In [59]:
#vhicle in position 14 in original datset
df.iloc[14]

cartyp    Cadillac Fleetwood
mpg                     10.4
cyl                        8
disp                   472.0
hp                       205
drat                    2.93
wt                      5.25
qsec                   17.98
vs                         0
am                         0
gear                       3
carb                       4
Name: 14, dtype: object